language: java
jdk:
  - oraclejdk8
# Skip default mvn install run by Travis
install: true
# Install dependencies, build the jar and run tests in quiet mode to
# avoid Travis CI 4MB log size limit
script: mvn -q clean install -Dmaven.test.redirectTestOutputToFile=true -B -V
notifications:
  email:
    on_success: never
    on_failure: always
after_success:
  # Run cobertura analysis and send report to Coveralls
  - mvn cobertura:cobertura coveralls:report -Dmaven.test.redirectTestOutputToFile=true
cache:
  # Cache maven dependencies to speed up the build
  directories:
  - $HOME/.m2
deploy:
  provider: heroku
  api_key: "60dffffb-8734-4e21-aef0-3db3f0ace717"
  app: idea-hub-d
